version: '3.3'

services:
  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8888
    volumes:
      - ./:/code/
    ports:
      - "8888:8888"
